### ISSUE TITLE
在Windows英文版文本显示错误

### ISSUE THREAD

**Issue by Ziyang-Bai** [ShaderFallback/CpuRamGet#3]
在windows10英文版中,无法正确的显示控制台字符。即使使用在cmd和powershell均可正常显示中文的黑体也无法解决该问题，在Windows10中文版使用任意字体（包括黑体）显示正常。
![图片](https://github.com/user-attachments/assets/043bdc4d-07aa-43ea-89f9-a13754cdfd31)

**Comment by ShaderFallback** [comment]
可能由于 GBK 编码,英文版系统不包含导致, 后续将改为 UTF-8打包, 你也可以在键盘-输入-手动添加中文语言包解决, 发送数据应该是正确的, 这个界面可以先忽略
