### ISSUE TITLE
无法获取正确的Cpu利用率

### ISSUE THREAD

**Issue by FarStar-CN** [ShaderFallback/CpuRamGet#4]
如图所示，采用最新版本客户端v0.1时，无法获取正确的cpu利用率信息，同时OpenHardwareMonitor亦是如此。
![Uploading b00bfd2a-41fa-454f-b977-46268b50433f.png…]()

**Comment by FarStar-CN** [comment]
![b00bfd2a-41fa-454f-b977-46268b50433f](https://github.com/user-attachments/assets/92b5a292-0475-45e2-9dab-4777f0a86716)

**Comment by ShaderFallback** [comment]
可以下载新版 OpenHardwareMonitor 看能否正常获取, 内部是直接调用 OpenHardwareMonitorLib.dll  库来获取的

**Comment by ShaderFallback** [comment]
建议将问题同时反馈至 [https://github.com/openhardwaremonitor/openhardwaremonitor/issues，](https://github.com/openhardwaremonitor/openhardwaremonitor/issues%EF%BC%8C) 他们更新了踢我一下 ：）

**Comment by ShaderFallback** [comment]
最新版更改使用LibreHardwareMonitor库
https://github.com/ShaderFallback/CpuRamGet/releases/tag/v0.2
