### ISSUE TITLE
建议更换掉openhardwaremonitor来解决cpu占用率显示偏低的问题

### ISSUE THREAD

**Issue by Tubare** [ShaderFallback/CpuRamGet#6]
电脑端软件使用了[openhardwaremonitor](https://github.com/openhardwaremonitor/openhardwaremonitor)来获取cpu等硬件信息，但是openhardwaremonitor存在一些问题导致获取的cpu占用率始终远远低于任务管理器。现在openhardwaremonitor已经多年没有更新，bug修复无望。希望作者能改用其他的硬件信息获取方式。

**Comment by ShaderFallback** [comment]
有推荐么

**Comment by Tubare** [comment]
LibreHardwareMonitor&nbsp; &nbsp; &nbsp;LibreHardwareMonitor/LibreHardwareMonitor at v0.9.3
HWiNFO&nbsp; &nbsp; &nbsp;About HWiNFO Software - Professional System Information &amp; Diagnostics




vickyau
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShaderFallback/CpuRamGet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月11日(星期一) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShaderFallback/CpuRamGet] 建议更换掉openhardwaremonitor来解决cpu占用率显示偏低的问题 (Issue #6)





 
有推荐么

**Comment by Tubare** [comment]
[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)
[psutil](https://github.com/giampaolo/psutil)

**Comment by ShaderFallback** [comment]
最新版更改使用LibreHardwareMonitor库
https://github.com/ShaderFallback/CpuRamGet/releases/tag/v0.2
